# Generated by Django 2.1.5 on 2020-07-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
